resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException

    instances:
      service1:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service1ExceptionPredicate
      service2:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service2ExceptionPredicate
      service3:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service3ExceptionPredicate
      service4:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service4ExceptionPredicate
      service5:
        baseConfig: default
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service5ExceptionPredicate

  circuitbreaker:
    configs:
      default:
        minimum-number-of-calls: 10
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 5000 #Time in milliseconds, in which the circuit breaker is to stay in open state before moving to half-open state
        failureRateThreshold: 60 #The Threshold Percentage Above Which the Circuit Breaker will move from Closed to Open State.
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      service1:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service1ExceptionPredicate
      service2:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service2ExceptionPredicate
      service3:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service3ExceptionPredicate
      service4:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service4ExceptionPredicate
      service5:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service5ExceptionPredicate

  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default
