resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 5
        waitDuration: 5s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
          - org.springframework.web.client.HttpServerErrorException

    instances:
      service1:
        baseConfig: default
        result-predicate: com.amsidh.mvc.result.predicate.Service1ResultPredicate        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service1ExceptionPredicate          
      service2:
        baseConfig: default
        result-predicate: com.amsidh.mvc.result.predicate.Service2ResultPredicate
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service2ExceptionPredicate
      service3:
        baseConfig: default
        result-predicate: com.amsidh.mvc.result.predicate.Service3ResultPredicate
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service3ExceptionPredicate
      service4:
        baseConfig: default
        result-predicate: com.amsidh.mvc.result.predicate.Service4ResultPredicate
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service4ExceptionPredicate
      service5:
        baseConfig: default
        result-predicate: com.amsidh.mvc.result.predicate.Service5ResultPredicate
        retry-exception-predicate: com.amsidh.mvc.exception.predicate.Service5ExceptionPredicate

  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 1s
        failureRateThreshold: 10 # percentage
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      service1:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service1ExceptionPredicate
      service2:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service2ExceptionPredicate
      service3:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service3ExceptionPredicate
      service4:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service4ExceptionPredicate
      service5:
        baseConfig: default
        record-failure-predicate: com.amsidh.mvc.exception.predicate.Service5ExceptionPredicate

  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      service1:
        baseConfig: default
      service2:
        baseConfig: default
      service3:
        baseConfig: default
      service4:
        baseConfig: default
      service5:
        baseConfig: default
